<a href="https://colab.research.google.com/github/shrishtinigam/Chronic-Kidney-Disease-Prediction/blob/main/CKD_D1_Logistic_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

DATASET 1 LOGISTIC REGRESSION

In [ ]:
import pandas as pd           #chronic kidney disease
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [ ]:
df=pd.read_csv('/content/new_model.csv')
df

,Bp,Sg,Al,Su,Rbc,Bu,Sc,Sod,Pot,Hemo,Wbcc,Rbcc,Htn,Class
0,80.0,1.020,1.0,0.0,1.0,36.0,1.2,137.53,4.63,15.4,7800.0,5.20,1.0,1
1,50.0,1.020,4.0,0.0,1.0,18.0,0.8,137.53,4.63,11.3,6000.0,4.71,0.0,1
2,80.0,1.010,2.0,3.0,1.0,53.0,1.8,137.53,4.63,9.6,7500.0,4.71,0.0,1
3,70.0,1.005,4.0,0.0,1.0,56.0,3.8,111.00,2.50,11.2,6700.0,3.90,1.0,1
4,80.0,1.010,2.0,0.0,1.0,26.0,1.4,137.53,4.63,11.6,7300.0,4.60,0.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,80.0,1.020,0.0,0.0,1.0,49.0,0.5,150.00,4.90,15.7,6700.0,4.90,0.0,0
396,70.0,1.025,0.0,0.0,1.0,31.0,1.2,141.00,3.50,16.5,7800.0,6.20,0.0,0
397,80.0,1.020,0.0,0.0,1.0,26.0,0.6,137.00,4.40,15.8,6600.0,5.40,0.0,0
398,60.0,1.025,0.0,0.0,1.0,50.0,1.0,135.00,4.90,14.2,7200.0,5.90,0.0,0
399,80.0,1.025,0.0,0.0,1.0,18.0,1.1,141.00,3.50,15.8,6800.0,6.10,0.0,0

In [ ]:
X=df.drop(columns='Class',axis=1)
Y=df['Class']
# Normalizing
scaler=StandardScaler()
standardized_data=scaler.fit_transform(X)
print(standardized_data)
# Splitting the data into train and test
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2,random_state =42)

[[ 2.63379226e-01  4.21485600e-01 -1.18041644e-02 ... -2.40505799e-01
   5.85900177e-01  1.30997921e+00]
 [-1.96549998e+00  4.21485600e-01  2.34902872e+00 ... -9.54773379e-01
   2.05537202e-03 -7.67209735e-01]
 [ 2.63379226e-01 -1.42107440e+00  7.75140131e-01 ... -3.59550396e-01
   2.05537202e-03 -7.67209735e-01]
 ...
 [ 2.63379226e-01  4.21485600e-01 -7.98748460e-01 ... -7.16684186e-01
   8.24204178e-01 -7.67209735e-01]
 [-1.22254025e+00  1.34276560e+00 -7.98748460e-01 ... -4.78594992e-01
   1.41996418e+00 -7.67209735e-01]
 [ 2.63379226e-01  1.34276560e+00 -7.98748460e-01 ... -6.37321121e-01
   1.65826818e+00 -7.67209735e-01]]

In [ ]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
model.fit(X_train,Y_train)
print(model.score(X_test,Y_test))
predicts=model.predict(X_test)

0.9625

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,

In [ ]:
from sklearn.metrics import precision_score,recall_score,accuracy_score
print('Precision: %.3f' % precision_score(Y_test,predicts))
print('Recall: %.3f' % recall_score(Y_test, predicts))
print('Accuracy: %.3f' % accuracy_score(Y_test, predicts))

Precision: 0.980
Recall: 0.962
Accuracy: 0.963